Alias: $sct = http://snomed.info/sct

Instance: HomehospAzacitidineQuestionnaireResponseExample
InstanceOf: QuestionnaireResponse
Title: "Azacitidine questionnairesponse home hospitalization"
Description: "Response to questionnaire containing the necessary information for the home hospitalization of a patient treated with Azacitidine."
Usage: #example
* questionnaire = "http://hl7belgium.org/fhir/patient-monitoring/Questionnaire/homehosp-azacitidine"
* status = #completed
* subject = Reference(Patient/Patient-123)
* authored = "2025-11-19T11:08:00.5813903+01:00"
* item[0].linkId = "NursingAssessment"
* item[=].text = "Verpleegkundig assessment"
* item[=].item[0].linkId = "MedicationStorage"
* item[=].item[=].text = "MedicationStorage"
* item[=].item[=].item.linkId = "A1_MedicationStorage"
* item[=].item[=].item.text = "Zijn er opmerkingen of bezorgdheden omtrent de (correcte) thuisbewaring van de medicatie?"
* item[=].item[=].item.answer.valueCoding = $sct#710977001 "Safe storage and management of medication"
* item[=].item[+].linkId = "ObservationParameters"
* item[=].item[=].text = "Observatie parameters"
* item[=].item[=].item[0].linkId = "B1_BodyTemperature"
* item[=].item[=].item[=].text = "Lichaamstemperatuur:"
* item[=].item[=].item[=].answer.valueDecimal = 36
* item[=].item[=].item[+].linkId = "B2_HeartRate"
* item[=].item[=].item[=].text = "Pols:"
* item[=].item[=].item[=].answer.valueDecimal = 66
* item[=].item[=].item[+].linkId = "B3_SystolicBloodPressure"
* item[=].item[=].item[=].text = "Bloeddruk systolisch:"
* item[=].item[=].item[=].answer.valueDecimal = 120
* item[=].item[=].item[+].linkId = "B4_DiastolicBloodPressure"
* item[=].item[=].item[=].text = "Bloeddruk diastolisch:"
* item[=].item[=].item[=].answer.valueDecimal = 71
* item[=].item[=].item[+].linkId = "B5_OxygenSaturation"
* item[=].item[=].item[=].text = "Zuurstofsaturatie (enkel uitvoeren bij hoest en kortademigheid)"
* item[=].item[=].item[=].answer.valueDecimal = 98
* item[=].item[+].linkId = "Contraindications"
* item[=].item[=].text = "Contraindications"
* item[=].item[=].item[0].linkId = "C1_ContraindicationPresent"
* item[=].item[=].item[=].text = "Zijn er tegenindicaties voor toediening?"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[=].item[+].linkId = "C3_FeverChills"
* item[=].item[=].item[=].text = "Koorts , koude rillingen, zich ziek voelen"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[=].item[+].linkId = "C4_OralIntake"
* item[=].item[=].item[=].text = "Geen orale intake (tgv verminderde eetlust of smaakverandering)"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[=].item[+].linkId = "C5_SevereNausea"
* item[=].item[=].item[=].text = "Ernstige misselijkheid (dwz misselijkheid met onvoldoende orale intake)"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[=].item[+].linkId = "C6_SevereDyspnea"
* item[=].item[=].item[=].text = "Toegenomen kortademigheid en/of ernstige kortademigheid (dwz kortademigheid in rust/zonder inspanning en/of kortademigheid die hindert bij de dagelijkse activiteiten) (Trastuzumab, Azacitidine)"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[=].item[+].linkId = "C7_NewCoughDyspnea"
* item[=].item[=].item[=].text = "Nieuwe of toegenomen productieve of droge hoest, met of zonder dyspnoe"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[=].item[+].linkId = "C8_GeneralDecline"
* item[=].item[=].item[=].text = "Algemene achteruitgang"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No"
* item[=].item[+].linkId = "SymptomBurden"
* item[=].item[=].text = "SymptomBurden"
* item[=].item[=].item[0].linkId = "D1_Nausea"
* item[=].item[=].item[=].text = "Misselijkheid"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D2_Vomiting"
* item[=].item[=].item[=].text = "Braken"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D3_DecreasedAppetite"
* item[=].item[=].item[=].text = "Verminderde eetlust of smaakverandering"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D4_Diarrhea"
* item[=].item[=].item[=].text = "Buikloop"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D5_Constipation"
* item[=].item[=].item[=].text = "Verstopping"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D6_Fatigue"
* item[=].item[=].item[=].text = "Vermoeidheid/futloosheid"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D7_Pain"
* item[=].item[=].item[=].text = "Pijn"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D8_SkinRash"
* item[=].item[=].item[=].text = "Huiduitslag"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D9_PsychosocialBurden"
* item[=].item[=].item[=].text = "Psychosociale belasting"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D10_Dyspnea"
* item[=].item[=].item[=].text = "Kortademigheid"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[=].item[=].item[+].linkId = "D11_Cough"
* item[=].item[=].item[=].text = "Hoest"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3"
* item[+].linkId = "Assignment"
* item[=].text = "Assignment"
* item[=].item[0].linkId = "MedicationPreparation"
* item[=].item[=].text = "Voorbereiding medicatietoediening"
* item[=].item[=].item.linkId = "E1_PreparationCorrect"
* item[=].item[=].item.text = "Kon de medicatie worden bereid volgens de procedure?"
* item[=].item[=].item.answer.valueCoding = $sct#373066001 "Yes"
* item[=].item[+].linkId = "MedicationAdministration"
* item[=].item[=].text = "MedicationAdministration"
* item[=].item[=].item.linkId = "E3_AdministrationCorrect"
* item[=].item[=].item.text = "Kon de medicatie exact volgens de procedure worden toegediend (er waren geen afwijkingen)?"
* item[=].item[=].item.answer.valueCoding = $sct#373066001 "Yes"