Alias: $sct = http://snomed.info/sct

Instance: AzacitidineV1response
InstanceOf: QuestionnaireResponse
Title: "Azacitidine questionnairesponse home hospitalization"
Description: "Response to questionnaire containing the necessary information for the home hospitalization of a patient treated with Azacitidine."
Usage: #example
* questionnaire = "Questionnaire/AzacitidineV1"
* status = #completed
* subject = Reference(Patient/7d95006c-f858-47e4-95f1-a90e9836251e)
* authored = "2025-11-19T11:08:00.5813903+01:00"
* item[0].linkId = "Verpleegkundigassessment"
* item[=].text = "Verpleegkundig assessment"
* item[=].item[0].linkId = "Bewaring"
* item[=].item[=].text = "Bewaring"
* item[=].item[=].item.linkId = "A1_Bewaring"
* item[=].item[=].item.text = "Zijn er opmerkingen of bezorgdheden omtrent de (correcte) thuisbewaring van de medicatie?"
* item[=].item[=].item.answer.valueCoding = $sct#710977001 "Safe storage of medication"
* item[=].item[+].linkId = "Observatieparameters"
* item[=].item[=].text = "Observatie parameters"
* item[=].item[=].item[0].linkId = "B1_Temperatuur"
* item[=].item[=].item[=].text = "Lichaamstemperatuur:"
* item[=].item[=].item[=].answer.valueDecimal = 36
* item[=].item[=].item[+].linkId = "B2_Pols"
* item[=].item[=].item[=].text = "Pols:"
* item[=].item[=].item[=].answer.valueDecimal = 66
* item[=].item[=].item[+].linkId = "B3_BloeddrukSystolisch"
* item[=].item[=].item[=].text = "Bloeddruk systolisch:"
* item[=].item[=].item[=].answer.valueDecimal = 120
* item[=].item[=].item[+].linkId = "B4_BloeddrukDiastolisch"
* item[=].item[=].item[=].text = "Bloeddruk diastolisch:"
* item[=].item[=].item[=].answer.valueDecimal = 71
* item[=].item[=].item[+].linkId = "B5_Zuurstofsaturatie"
* item[=].item[=].item[=].text = "Zuurstofsaturatie (enkel uitvoeren bij hoest en kortademigheid)"
* item[=].item[=].item[=].answer.valueDecimal = 98
* item[=].item[+].linkId = "Tegenindicaties"
* item[=].item[=].text = "Tegenindicaties"
* item[=].item[=].item[0].linkId = "C1_Tegenindicatie"
* item[=].item[=].item[=].text = "Zijn er tegenindicaties voor toediening?"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[=].item[+].linkId = "C3_KoortsRillingen"
* item[=].item[=].item[=].text = "Koorts , koude rillingen, zich ziek voelen"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[=].item[+].linkId = "C4_OraleIntake"
* item[=].item[=].item[=].text = "Geen orale intake (tgv verminderde eetlust of smaakverandering)"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[=].item[+].linkId = "C5_MisselijkheidErnstig"
* item[=].item[=].item[=].text = "Ernstige misselijkheid (dwz misselijkheid met onvoldoende orale intake)"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[=].item[+].linkId = "C6_KortademigheidErnstig"
* item[=].item[=].item[=].text = "Toegenomen kortademigheid en/of ernstige kortademigheid (dwz kortademigheid in rust/zonder inspanning en/of kortademigheid die hindert bij de dagelijkse activiteiten) (Trastuzumab, Azacitidine)"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[=].item[+].linkId = "C7_HoestDyspnoe"
* item[=].item[=].item[=].text = "Nieuwe of toegenomen productieve of droge hoest, met of zonder dyspnoe"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[=].item[+].linkId = "C8_Achteruitgang"
* item[=].item[=].item[=].text = "Algemene achteruitgang"
* item[=].item[=].item[=].answer.valueCoding = $sct#373067005 "No (qualifier value)"
* item[=].item[+].linkId = "Symptoomlast"
* item[=].item[=].text = "Symptoomlast"
* item[=].item[=].item[0].linkId = "D1_Misselijkheid"
* item[=].item[=].item[=].text = "Misselijkheid"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D2_Braken"
* item[=].item[=].item[=].text = "Braken"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D3_VerminderdeEetlust"
* item[=].item[=].item[=].text = "Verminderde eetlust of smaakverandering"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D4_Buikloop"
* item[=].item[=].item[=].text = "Buikloop"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D5_Verstopping"
* item[=].item[=].item[=].text = "Verstopping"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D6_Vermoeidheid"
* item[=].item[=].item[=].text = "Vermoeidheid/futloosheid"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D7_Pijn"
* item[=].item[=].item[=].text = "Pijn"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D8_Huiduitslag"
* item[=].item[=].item[=].text = "Huiduitslag"
* item[=].item[=].item[=].answer.valueCoding = $sct#444456001 "Grade 1 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D9_Psychosociaal"
* item[=].item[=].item[=].text = "Psychosociale belasting"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D10_Kortademigheid"
* item[=].item[=].item[=].text = "Kortademigheid"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[=].item[=].item[+].linkId = "D11_Hoest"
* item[=].item[=].item[=].text = "Hoest"
* item[=].item[=].item[=].answer.valueCoding = $sct#444431007 "Grade 0 on a scale of 0 to 3 (qualifier value)"
* item[+].linkId = "Opdracht"
* item[=].text = "Opdracht"
* item[=].item[0].linkId = "Voorbereidingmedicatietoediening"
* item[=].item[=].text = "Voorbereiding medicatietoediening"
* item[=].item[=].item.linkId = "E1_BereidingCorrect"
* item[=].item[=].item.text = "Kon de medicatie worden bereid volgens de procedure?"
* item[=].item[=].item.answer.valueCoding = $sct#373066001 "Yes (qualifier value)"
* item[=].item[+].linkId = "Medicatietoediening"
* item[=].item[=].text = "Medicatietoediening"
* item[=].item[=].item.linkId = "E3_ToedieningCorrect"
* item[=].item[=].item.text = "Kon de medicatie exact volgens de procedure worden toegediend (er waren geen afwijkingen)?"
* item[=].item[=].item.answer.valueCoding = $sct#373066001 "Yes (qualifier value)"