Alias: $sct = http://snomed.info/sct

Instance: OPATContinuInfuusV1response
InstanceOf: QuestionnaireResponse
Usage: #example
* questionnaire = "Questionnaire/OPATContinuInfuusV1"
* status = #completed
* subject = Reference(Patient/af69876d-628e-47f6-a824-6c0fa6d23be4)
* authored = "2025-11-21T11:49:11.8445723+01:00"
* item.linkId = "Verpleegkundigassessment"
* item.text = "Verpleegkundig assessment"
* item.item[0].linkId = "Bewaring"
* item.item[=].text = "Bewaring"
* item.item[=].item.linkId = "87Zijneropmerkingenofbezorgdhedenomtrentdecorrectethuisbewaringvandemedicatie"
* item.item[=].item.text = "Zijn er opmerkingen of bezorgdheden omtrent de (correcte) thuisbewaring van de medicatie?"
* item.item[=].item.answer.valueCoding = $sct#710977001 "Safe storage of medication"
* item.item[+].linkId = "Voorbereidingmedicatietoediening"
* item.item[=].text = "Voorbereiding medicatietoediening"
* item.item[=].item[0].linkId = "52Demedicatiewerdvolledigopgelosttoteenheldereoplossingzonderzichtbaredeeltjes"
* item.item[=].item[=].text = "De medicatie werd volledig opgelost tot een heldere oplossing zonder zichtbare deeltjes"
* item.item[=].item[=].answer.valueCoding = $sct#373066001 "Yes (qualifier value)"
* item.item[=].item[+].linkId = "24GewichtvanvolleInfusornetvoornieuwetoediening"
* item.item[=].item[=].text = "Gewicht van volle Infusor net voor nieuwe toediening"
* item.item[=].item[=].answer.valueDecimal = 307
* item.item[=].item[+].linkId = "79Gewichtbijafkoppelenvanlegeinfusor"
* item.item[=].item[=].text = "Gewicht bij afkoppelen van lege infusor"
* item.item[=].item[=].answer.valueDecimal = 123
* item.item[=].item[+].linkId = "87Bijkomendeobservatieindienvantoepassing"
* item.item[=].item[=].text = "Bijkomende observatie:(indien van toepassing)"
* item.item[=].item[=].answer.valueString = "Infusor gisteren pas aangehangen om 13u45"
* item.item[+].linkId = "Medicatietoediening"
* item.item[=].text = "Medicatietoediening"
* item.item[=].item.linkId = "13Kondemedicatieexactvolgensdeprocedurewordentoegedienderwarengeenafwijkingen"
* item.item[=].item.text = "Kon de medicatie exact volgens de procedure worden toegediend  (er waren geen afwijkingen)?"
* item.item[=].item.answer.valueCoding = $sct#373066001 "Yes (qualifier value)"
* item.item[+].linkId = "Vitaleparameters"
* item.item[=].text = "Vitale parameters"
* item.item[=].item[0].linkId = "98Lichaamstemperatuur"
* item.item[=].item[=].text = "Lichaamstemperatuur:"
* item.item[=].item[=].answer.valueDecimal = 36.1
* item.item[=].item[+].linkId = "2Pols"
* item.item[=].item[=].text = "Pols:"
* item.item[=].item[=].answer.valueDecimal = 95
* item.item[=].item[+].linkId = "70Bloeddruksystolisch"
* item.item[=].item[=].text = "Bloeddruk - systolisch"
* item.item[=].item[=].answer.valueDecimal = 131
* item.item[=].item[+].linkId = "19Bloeddrukdiastolisch"
* item.item[=].item[=].text = "Bloeddruk - diastolisch"
* item.item[=].item[=].answer.valueDecimal = 65
* item.item[+].linkId = "Observatieverbandinsteekplaats"
* item.item[=].text = "Observatie verband insteekplaats"
* item.item[=].item.linkId = "23Observatieverbandinsteekplaats"
* item.item[=].item.text = "Observatie verband insteekplaats"
* item.item[=].item.answer.valueCoding = $sct#17621005 "Normal (qualifier value)"
* item.item[+].linkId = "Observatieinsteekplaats"
* item.item[=].text = "Observatie insteekplaats"
* item.item[=].item.linkId = "1Observatieinsteekplaats"
* item.item[=].item.text = "Observatie insteekplaats"
* item.item[=].item.answer.valueCoding = $sct#17621005 "Normal (qualifier value)"
* item.item[+].linkId = "Observatiekatheter"
* item.item[=].text = "Observatie katheter"
* item.item[=].item.linkId = "97Observatiekatheter"
* item.item[=].item.text = "Observatie katheter"
* item.item[=].item.answer.valueCoding = $sct#17621005 "Normal (qualifier value)"
* item.item[+].linkId = "catheter-type"
* item.item[=].answer.valueCoding = $sct#445085009 "Tunneled central venous catheter"
* item.item[=].answer.extension.url = "http://example.org/fhir/StructureDefinition/lumen"
* item.item[=].answer.extension.valueCoding = $sct#257279004 "Single lumen catheter"
* item.item[+].linkId = "Nevenwerkingen"
* item.item[=].text = "Nevenwerkingen"
* item.item[=].item[0].linkId = "36Huiduitslag"
* item.item[=].item[=].text = "Huiduitslag"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "99Jeuk"
* item.item[=].item[=].text = "Jeuk"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "11Blarenloslatenvandehuid"
* item.item[=].item[=].text = "Blaren/loslaten van de huid"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "20Misselijkheid"
* item.item[=].item[=].text = "Misselijkheid"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "37Braken"
* item.item[=].item[=].text = "Braken"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "37Diarree"
* item.item[=].item[=].text = "Diarree"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "18Obstipatie"
* item.item[=].item[=].text = "Obstipatie"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "68Verminderdeeetlust"
* item.item[=].item[=].text = "Verminderde eetlust"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "74Pijnbijtoediening"
* item.item[=].item[=].text = "Pijn bij toediening"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "41Pijnalgemeen"
* item.item[=].item[=].text = "Pijn (algemeen)"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "57Moe"
* item.item[=].item[=].text = "Moe"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "24Rillingen"
* item.item[=].item[=].text = "Rillingen"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "1Candidiaseschimmelinfectie"
* item.item[=].item[=].text = "Candidiase (schimmelinfectie)"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "48Gewrichtspijn"
* item.item[=].item[=].text = "Gewrichtspijn"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "80Ademhalingsproblemen"
* item.item[=].item[=].text = "Ademhalingsproblemen"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"
* item.item[=].item[+].linkId = "79Zwellinggezichttong"
* item.item[=].item[=].text = "Zwelling gezicht/tong"
* item.item[=].item[=].answer.valueCoding = $sct#2667000 "Absent (qualifier value)"